---
- hosts: all
  become: yes
  tasks:
    - name: Append proxy settings to environment file
      shell: |
        awk '!seen[$0]++' /home/vagrant/tdata/proxy.conf /etc/environment > /etc/environment

